### ISSUE TITLE
`get_preds` isn't compatible with `Interpretation.from_learner()`

### ISSUE THREAD

**Issue by rsomani95** [muellerzr/fastinference#10]
[`Interpretation.from_learner`](https://github.com/fastai/fastai2/blob/bf455de9bc37c76f7f92b3c43227ef9d4779b614/fastai2/interpret.py#L23) calls`Learner.get_preds()`, which this package replaces, causing it to break. 

I think fixing it should be fairly straightforward.

**Comment by muellerzr** [comment]
It’s actually not, this is designed to be used on inference only and it’s own interpretability modules so they’re not compatable. I’d recommend not importing fastinference until after you’ve finished wanting anything standard in the fastai library specifically.

**Comment by m-ali-awan** [comment]
Hi Mueller, sorry I am here again.
But I am getting this same issue of get_preds:
AttributeError: 'ClassificationInterpretation' object has no attribute 'get_preds'

So, how to address it?

Thanks..
