### ISSUE TITLE
SHAP won't install "from fastinference.tabular import *" Fails

### ISSUE THREAD

**Issue by md598** [muellerzr/fastinference#15]
Trying to install, use SHAP. 

!pip install fastinference fastai -q, this works

from fastinference.tabular import * produces:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-122-b6943c36f403> in <module>()
----> 1 from fastinference.tabular import *

3 frames
/usr/local/lib/python3.6/dist-packages/fastinference/tabular/__init__.py in <module>()
      3     raise ImportError("The interp module is not installed.")
      4 
----> 5 from .shap import *
      6 from .interpretation import *

/usr/local/lib/python3.6/dist-packages/fastinference/tabular/shap/__init__.py in <module>()
----> 1 from .interp import *

/usr/local/lib/python3.6/dist-packages/fastinference/tabular/shap/interp.py in <module>()
      4 
      5 # Cell
----> 6 from .core import _prepare_data, _predict
      7 import shap
      8 from fastai.tabular.all import *

/usr/local/lib/python3.6/dist-packages/fastinference/tabular/shap/core.py in <module>()
      4 
      5 # Cell
----> 6 from fastai.tabular.all import *
      7 
      8 # Cell

ModuleNotFoundError: No module named 'fastai.tabular.all'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

Have also tried: !pip install fastinference[interp] -q and no luck. Thanks!

**Comment by muellerzr** [comment]
I'd presume you're using colab, as this means you have the wrong version of fastai. You need to install with `--upgrade`. Also you need to install with `interp` as the README states.

**Comment by md598** [comment]
Using colab. Did upgrade fastai with
!pip install fastai --upgrade 
 and did 
!pip install fastinference[interp] per README, same issue. Any ideas?

**Comment by md598** [comment]
Copy/pasted in a bunch of the code from this notebook and it worked! https://github.com/muellerzr/fastinference/blob/master/nbs/02_shap.interp.ipynb
Hopefully that's insightful! Congrats on the new release! Got the book on order!

**Comment by muellerzr** [comment]
I didn't get an issue, did you make sure to restart your instance? I did the following steps:
```python
!pip install fastinference[interp] shap
!pip install fastai --upgrade
```
```python
from fastinference.tabular import *
```

Also, I had nothing to do with Jeremy & Sylvain's book :)

**Comment by md598** [comment]
It worked! Thank you!
