### ISSUE TITLE
TypeError: waterfall() got an unexpected keyword argument 'feature_names' 

### ISSUE THREAD

**Issue by henry090** [muellerzr/fastinference#24]
Hi. 
Pypi version of fastinference throws:

```
exp.waterfall_plot(row_idx=10)
TypeError: waterfall() got an unexpected keyword argument 'feature_names' 
```

**Comment by muellerzr** [comment]
Thanks! I noticed this too. It seems there was a radical change recently in shap. I'll look and try to pin the version today/tomorrow. This also would explain the sudden time-scale difference when passing in 100 rows into the interpreter

**Comment by muellerzr** [comment]
@henry090 can you try installing from git and using it?

```python
!pip install git+https://github.com/muellerzr/fastinference
```
Same imports

**Comment by henry090** [comment]
I get the same error:
```
TypeError: waterfall() got an unexpected keyword argument 'feature_names'

Detailed traceback: 
  File "/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastinference/tabular/shap/interp.py", line 60, in waterfall_plot
    return shap.waterfall_plot(exp_val, shap_vals[row_idx,:], feature_names=feat_names, **kwargs)
```

**Comment by muellerzr** [comment]
This has been fixed now. Reopen if you still have issues but I can confirm it in colab

**Comment by henry090** [comment]
Thanks. In fact, I manually installed ```shap==0.35.0``` and it worked.
