### ISSUE TITLE
Torchvision models do not seem to support `dynamic_axes` in ONNX export

### ISSUE THREAD

**Issue by FraPochetti** [muellerzr/fastinference#30]
Hi Zach,
we briefly interacted on [Discord](https://discord.com/channels/689892369998676007/737149430498721842/798569131758714920) about this problem and you kindly suggested to open an issue here as well.

My problem is explained [here](https://discuss.pytorch.org/t/dynamic-axes-not-working-as-expected-in-torch-oxxn-export-torchvision/106460).
According to this [conversation](https://github.com/pytorch/vision/issues/2311) it seems this is driven by torchvision not supporting `dynamic_axes` for ONNX quite yet. I have commented there, hoping to get a reply from the devs. 

On top of the code provided in the PyTorch forums, I have also:
* tried your solution
* tried adapting [this gist](https://gist.github.com/dxxz/3c40b5059bd5efe939ce96752d628158)

with no luck yet.

It would be great to hear your thoughts as I am running out of ideas! :)

**Comment by muellerzr** [comment]
Since this is not related to fastai/fastinference, only torchvision, I'm closing this.
