### ISSUE TITLE
feature importance returns a ModuleAttributeError

### ISSUE THREAD

**Issue by chsafouane** [muellerzr/fastinference#45]
I start by importing

```
from fastinference.tabular import *
from fastai.tabular.all import *
```

 and I execute the tutorial in the tabular-interpretation section line by line. When I get to this line  `fi = learn.feature_importance(df=df)`, I get the following error

![image](https://user-images.githubusercontent.com/31566323/110398548-5d9c0600-8074-11eb-83b1-06a9d1fe06a8.png)

**Comment by muellerzr** [comment]
@chsafouane try doing `from fastinference.tabular.interpretation import *` instead. Will update the tutorial
