### ISSUE TITLE
Returning N top predictions

### ISSUE THREAD

**Issue by andresti** [muellerzr/fastinference#55]
Hi,
I have a use case where I need multiple predictions and their probabilities - if the model is not confident enough in the prediction, the user gets a choice of N top predictions to choose the correct one themselves.

I've modified the fastinference code to implement this functionality (at the moment I just return a sorted list of all classes and their probabilities). Would you be interested in having it as a pull request? I haven't measured the speed and the code is a bit hacky at the moment, so I would need to clean it up first and integrate with the original functionality.

**Comment by muellerzr** [comment]
That's a bit too magic-y for me. Plus, you should already be able to do so with `get_preds`. Just pass in `act=noop` when getting predictions.

**Comment by andresti** [comment]
What does passing `act=noop` actually do? I can't see any difference and it doesn't seem that such parameter is used anywhere anyhow.

Anyway, `get_preds` only gives the label of the class with the largest probability, that's why I modified it. I guess I can calculate what I need from the probabilities array, but I figured it could be a bit faster if done inside `get_preds`.
