### ISSUE TITLE
CUDA Out of Memory When Running Inference on a Large Test Set (And Proposed Fixes)

### ISSUE THREAD

**Issue by rsomani95** [muellerzr/fastinference#7]
In [`inference.py`'s `get_preds`](https://github.com/muellerzr/fastinference/blob/8532bd6f9e6d86aa65bf6790b1c9d2b5a13dc2fe/fastinference/inference/inference.py) function, the inputs are being stored regardless of whether `fully_decoded` is `True` or `False`. These inputs are being stored _on the GPU_, and are only released from memory after the inference loop is finished.

As the size of the test set increases, the GPU will at some point run out of memory if the test set is large enough (In my test case, I ran out of memory with <50,000 items with an EfficientNet-B3A and image size of 224x224). 

There's 2 ways to fix this:
#### 1. store the inputs on CPU (I haven't tested this). 
```python
with torch.no_grad():
    if is_multi:
        for i in range(x.dls.n_inp):
            #inps[i].append(batch[i])
            inps[i].append(batch[i].cpu())
    else:
        #inps.append(batch[:x.dls.n_inp])
        inps.append(batch[:x.dls.n_inp].cpu())
    # rest of the loop
```

#### 2. Skip storing the inputs altogether if `fully_decoded is False`, as it's redundant. This should provide some speedup too. (Tested)
```python
with torch.no_grad():
    if fully_decoded:
        if is_multi:
            for i in range(x.dls.n_inp):
                inps[i].append(batch[i])
        else:
            inps.append(batch[:x.dls.n_inp])
    # rest of the loop
```

I've made this modification in my code and can vouch that it works. I can pass in arbitrarily long test sets and there's no issues.

---
I think (2) should be done regardless. I'm not sure about (1) as converting to `.cpu()` is an overhead, but perhaps we should leave this to the user (if they want to prioritise inference speed, they'd probably be skipping this anyways).

**Comment by muellerzr** [comment]
2 seems like a good solution, I'll test the speed on 1 here today later. Thanks for pointing this out!

**Comment by muellerzr** [comment]
Looks like 1 does shave a few seconds too, so I think we should just combine both! IF you want to put a PR in so you're on the contributors list feel free, otherwise I can do it :) 

Relevant code:
```python
    for batch in dl:
        with torch.no_grad():
            if fully decoded:
                if is_multi:
                    for i in range(x.dls.n_inp):
                        inps[i].append(batch[i].cpu())
                else:
                    inps.append(batch[:x.dls.n_inp].cpu())
            if decoded_loss or fully_decoded:
                out = x.model(*batch[:x.dls.n_inp])
                raw.append(out)
                dec_out.append(x.loss_func.decodes(out))
            else:
                raw.append(x.model(*batch[:x.dls.n_inp]))
```

**Comment by rsomani95** [comment]
Awesome! Interesting that it shaves off a few seconds; I’d have imagined otherwise. Perhaps having lesser numbers stored on the GPU speeds it up despite the overhead?

Sure, I’ll put in a PR :)

**Comment by muellerzr** [comment]
Probably! It brought it from 2.52 to 2.2s when I was doing `get_preds` on tabular and 25.2ms to 21/22ms on predict
